services:
  # --- Aplicação Streamlit ---
  commeatus-app:
    container_name: commeatus_app
    build: .
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - .:/app
    environment:
      - TZ=America/Maceio
      # Informamos ao App onde está o banco
      - DB_HOST=db
      - DB_NAME=commeatus_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    depends_on:
      - db
    restart: always

  # --- Background Worker ---
  worker:
    container_name: commeatus_worker
    build: .
    volumes:
      - .:/app
    environment:
      - TZ=America/Maceio
      - DB_HOST=db
      - DB_NAME=commeatus_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
    entrypoint: [ "conda", "run", "--no-capture-output", "-n", "commeatus_env", "python", "worker/main.py" ]
    restart: always

  # --- Acesso Jupyter/Arquivos ---
  file-system-access:
    container_name: commeatus_fs
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - TZ=America/Maceio
    command: >
      conda run --no-capture-output -n commeatus_env  jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    restart: always

  # --- NOVO: Banco de Dados PostgreSQL ---
  db:
    container_name: commeatus_db
    image: postgres:14-bullseye
    ports:
      - "5432:5432" # Libera acesso externo (DBeaver, etc)
    environment:
      - POSTGRES_DB=commeatus_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
