services:
  # --- Aplicação Streamlit ---
  commeatus-app:
    container_name: commeatus_app
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - TZ=America/Maceio
      # Informamos ao App onde está o banco
      - DB_HOST=db
      - DB_NAME=commeatus_db
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
    restart: always

  # --- NOVO: Banco de Dados PostgreSQL ---
  db:
    container_name: commeatus_db
    image: postgres:14-bullseye
    ports:
      - "5432:5432" # Libera acesso externo (DBeaver, etc)
    environment:
      - POSTGRES_DB=commeatus_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

# Persistência de dados (para não perder ao reiniciar)
volumes:
  postgres_data:
